module.exports = {
    game: 'test2',
    port: 8078,
    pingTimeout: 100000,
    pingInterval: 10000,
    logLevel: 3,
    turnTime: 60,
    maxTimeouts: 1,
    timeMode: 'reset_every_switch',
    timeStartMode: 'after_turn',
    addTime: 0,
    corTime: 5000,
    minTurns: 1,
    takeBacks: 1,
    loadRanksInRating: true,
    penalties: true,
    calcDraw: false,
    //mode: 'develop',
    gameModes: ['mode_1', 'mode_2'],
    modesAlias:{'mode_1':'mode first', 'mode_2': 'mode second'},
    adminList: ['448039'],
    adminPass: '1',
    enableIpGames: false,
    minUnfocusedTurns: 1
};